name: GitHub Actions Demo
run-name: ${{ github.actor }} estÃ¡ probando GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ El trabajo fue activado automÃ¡ticamente por un evento ${{ github.event_name }}."
      - run: echo "ğŸ§ Este trabajo se estÃ¡ ejecutando en un servidor ${{ runner.os }} alojado por GitHub!"
      - run: echo "ğŸ” El nombre de tu rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}."
      - name: Obtener cÃ³digo del repositorio
        uses: actions/checkout@v5
      - run: echo "ğŸ’¡ El repositorio ${{ github.repository }} ha sido clonado en el runner."
      - run: echo "ğŸ–¥ï¸ El workflow estÃ¡ listo para probar tu cÃ³digo en el runner."
      - name: Listar archivos del repositorio
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ El estado de este trabajo es ${{ job.status }}."
